<?php $page_title = 'Admin - Templates'; include __DIR__ . '/_nav.php'; ?>
<div class="admin-container">
<h1><i class="fas fa-layer-group"></i> Gerenciar Templates</h1>
<?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?php echo htmlspecialchars($_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
<?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?php echo htmlspecialchars($_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
<section class="admin-panel"><h2><?php echo $editingTemplate ? 'Editar Template' : 'Criar Novo Template'; ?></h2><form method="POST" action="index.php?page=admin/template-salvar" class="template-form"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrfToken); ?>"><input type="hidden" name="id" value="<?php echo (int)($editingTemplate['id'] ?? 0); ?>"><div class="grid"><label>Nome<input name="nome" required value="<?php echo htmlspecialchars($editingTemplate['nome'] ?? ''); ?>"></label><label>Slug<input name="slug" required value="<?php echo htmlspecialchars($editingTemplate['slug'] ?? ''); ?>"></label><label>Plano<select name="plano_requerido"><option value="gratuito" <?php echo ($editingTemplate['plano_requerido'] ?? '')==='gratuito'?'selected':''; ?>>Gratuito</option><option value="premium" <?php echo ($editingTemplate['plano_requerido'] ?? '')==='premium'?'selected':''; ?>>Premium</option><option value="profissional" <?php echo ($editingTemplate['plano_requerido'] ?? '')==='profissional'?'selected':''; ?>>Profissional</option></select></label><label>Ordem<input type="number" name="ordem" value="<?php echo (int)($editingTemplate['ordem'] ?? 0); ?>"></label></div><label>Descrição<textarea name="descricao"><?php echo htmlspecialchars($editingTemplate['descricao'] ?? ''); ?></textarea></label><label>Miniatura URL<input name="miniatura_url" value="<?php echo htmlspecialchars($editingTemplate['miniatura_url'] ?? ''); ?>"></label><label>HTML<textarea name="html_estrutura" rows="8" required><?php echo htmlspecialchars($editingTemplate['html_estrutura'] ?? ''); ?></textarea></label><label>CSS<textarea name="css_estilo" rows="8" required><?php echo htmlspecialchars($editingTemplate['css_estilo'] ?? ''); ?></textarea></label><label class="check"><input type="checkbox" name="ativo" <?php echo ($editingTemplate['ativo'] ?? 1) ? 'checked' : ''; ?>> Ativo</label><button class="btn-primary">Salvar Template</button></form></section>
<?php if ($previewTemplate): ?><section class="admin-panel"><h2>Preview: <?php echo htmlspecialchars($previewTemplate['nome']); ?></h2><style><?php echo $previewTemplate['css_estilo']; ?></style><div class="template-preview-box"><?php echo str_replace(['{{nome}}','{{profissao}}','{{email}}','{{telefone}}','{{endereco}}','{{sobre}}','{{foto}}','{{experiencias}}','{{educacoes}}','{{habilidades}}'], ['Nome Exemplo','Profissão','email@exemplo.com','900000000','Luanda','Resumo profissional...','<i class="fas fa-user-circle"></i>','<div class="experiencia-item"><h4>Cargo</h4><p class="empresa">Empresa</p><p class="periodo">2024-2026</p><p>Descrição</p></div>','<div class="educacao-item"><h4>Curso</h4><p class="instituicao">Instituição</p><p class="periodo">2020-2024</p></div>','<div class="habilidades-container"><ul><li>PHP</li><li>Gestão</li></ul></div>'], $previewTemplate['html_estrutura']); ?></div></section><?php endif; ?>
<section class="admin-panel"><h2>Templates existentes</h2><div class="table-responsive"><table><thead><tr><th>Nome</th><th>Slug</th><th>Plano</th><th>Ativo</th><th>Ações</th></tr></thead><tbody><?php foreach($templates as $tpl): ?><tr><td><?php echo htmlspecialchars($tpl['nome']); ?></td><td><?php echo htmlspecialchars($tpl['slug']); ?></td><td><?php echo htmlspecialchars($tpl['plano_requerido']); ?></td><td><?php echo $tpl['ativo']?'Sim':'Não'; ?></td><td><a href="index.php?page=admin/templates&editar=<?php echo (int)$tpl['id']; ?>">Editar</a> | <a href="index.php?page=admin/templates&preview=<?php echo (int)$tpl['id']; ?>">Preview</a> | <a onclick="return confirm('Excluir template?')" href="index.php?page=admin/template-excluir&id=<?php echo (int)$tpl['id']; ?>">Excluir</a></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<style>.admin-container{max-width:1280px;margin:0 auto;padding:34px 20px}.admin-tabs{max-width:1280px;margin:24px auto 0;padding:0 20px;display:flex;gap:10px;flex-wrap:wrap}.admin-tabs a{background:#fff;border:1px solid #e5e7eb;color:#2c3e66;text-decoration:none;padding:10px 14px;border-radius:10px}.admin-panel{background:#fff;border-radius:16px;padding:22px;margin:18px 0;box-shadow:0 8px 28px rgba(0,0,0,.06)}.template-form{display:grid;gap:14px}.template-form .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.template-form label{display:grid;gap:5px}.template-form input,.template-form select,.template-form textarea{padding:10px;border:1px solid #ddd;border-radius:8px;font:inherit}.check{display:flex!important;align-items:center;gap:8px}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #eee;text-align:left}.table-responsive{overflow-x:auto}.template-preview-box{padding:20px;background:#f8f9fa;overflow:auto}.alert{padding:12px;border-radius:8px;margin:12px 0}.alert-success{background:#d4edda}.alert-danger{background:#f8d7da}</style>
