<?php $page_title = 'Admin - Usuários'; include __DIR__ . '/_nav.php'; $totalPages = max(1, (int)ceil($usersResult['total'] / $usersResult['per_page'])); ?>
<div class="admin-container">
    <h1><i class="fas fa-users"></i> Gerenciar Usuários</h1>
    <?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?php echo htmlspecialchars($_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
    <?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?php echo htmlspecialchars($_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
    <form class="admin-search" method="GET"><input type="hidden" name="page" value="admin/usuarios"><input type="search" name="q" value="<?php echo htmlspecialchars($search); ?>" placeholder="Buscar por nome ou email"><button class="btn-primary">Buscar</button></form>
    <?php if ($selectedUser): ?>
        <section class="admin-panel"><h2>Editar usuário</h2><form method="POST" action="index.php?page=admin/usuario-salvar" class="admin-form"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrfToken); ?>"><input type="hidden" name="id" value="<?php echo (int)$selectedUser['id']; ?>"><label>Nome<input name="nome_completo" value="<?php echo htmlspecialchars($selectedUser['nome_completo']); ?>" required></label><label>Email<input type="email" name="email" value="<?php echo htmlspecialchars($selectedUser['email']); ?>" required></label><label>Plano<select name="plano"><option value="gratuito" <?php echo $selectedUser['plano']==='gratuito'?'selected':''; ?>>Gratuito</option><option value="premium" <?php echo $selectedUser['plano']==='premium'?'selected':''; ?>>Premium</option><option value="profissional" <?php echo $selectedUser['plano']==='profissional'?'selected':''; ?>>Profissional</option></select></label><label class="check"><input type="checkbox" name="ativo" <?php echo $selectedUser['ativo']?'checked':''; ?>> Ativo</label><label class="check"><input type="checkbox" name="is_admin" <?php echo !empty($selectedUser['is_admin'])?'checked':''; ?>> Administrador</label><button class="btn-primary">Salvar</button></form></section>
    <?php endif; ?>
    <?php if ($selectedUser && !empty($_GET['curriculos'])): ?>
        <section class="admin-panel"><h2>Currículos de <?php echo htmlspecialchars($selectedUser['nome_completo']); ?></h2><?php foreach ($userResumes as $resume): ?><div class="admin-list-row"><span><?php echo htmlspecialchars($resume['titulo']); ?> <small><?php echo htmlspecialchars($resume['template_nome']); ?></small></span><a class="btn-sm" href="index.php?page=editor&id=<?php echo (int)$resume['id']; ?>">Ver</a></div><?php endforeach; if(empty($userResumes)): ?><p>Nenhum currículo encontrado.</p><?php endif; ?></section>
    <?php endif; ?>
    <section class="admin-panel"><div class="table-responsive"><table><thead><tr><th>Nome</th><th>Email</th><th>Plano</th><th>Estado</th><th>Admin</th><th>Ações</th></tr></thead><tbody><?php foreach ($usersResult['data'] as $row): ?><tr><td><?php echo htmlspecialchars($row['nome_completo']); ?></td><td><?php echo htmlspecialchars($row['email']); ?></td><td><?php echo htmlspecialchars($row['plano']); ?></td><td><?php echo $row['ativo'] ? 'Ativo' : 'Bloqueado'; ?></td><td><?php echo !empty($row['is_admin']) ? 'Sim' : 'Não'; ?></td><td><a href="index.php?page=admin/usuarios&editar=<?php echo (int)$row['id']; ?>">Editar</a> | <a href="index.php?page=admin/usuarios&curriculos=<?php echo (int)$row['id']; ?>">CVs</a> | <a href="index.php?page=admin/usuario-toggle&id=<?php echo (int)$row['id']; ?>">Bloquear/Desbloquear</a> | <a onclick="return confirm('Excluir usuário?')" href="index.php?page=admin/usuario-excluir&id=<?php echo (int)$row['id']; ?>">Excluir</a></td></tr><?php endforeach; ?></tbody></table></div><div class="pagination"><?php for($i=1;$i<=$totalPages;$i++): ?><a href="index.php?page=admin/usuarios&p=<?php echo $i; ?>&q=<?php echo urlencode($search); ?>" class="<?php echo $i===$usersResult['page']?'active':''; ?>"><?php echo $i; ?></a><?php endfor; ?></div></section>
</div>
<style>.admin-container{max-width:1280px;margin:0 auto;padding:34px 20px}.admin-tabs{max-width:1280px;margin:24px auto 0;padding:0 20px;display:flex;gap:10px;flex-wrap:wrap}.admin-tabs a{background:#fff;border:1px solid #e5e7eb;color:#2c3e66;text-decoration:none;padding:10px 14px;border-radius:10px}.admin-panel{background:#fff;border-radius:16px;padding:22px;margin:18px 0;box-shadow:0 8px 28px rgba(0,0,0,.06)}.admin-search,.admin-form{display:flex;gap:12px;flex-wrap:wrap}.admin-search input,.admin-form input,.admin-form select{padding:10px;border:1px solid #ddd;border-radius:8px}.admin-form label{display:grid;gap:4px}.admin-form .check{display:flex;align-items:center;gap:6px}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #eee;text-align:left}.table-responsive{overflow-x:auto}.pagination a{display:inline-block;margin:10px 4px;padding:8px 12px;background:#eef2f7;border-radius:8px;text-decoration:none}.pagination .active{background:#2c3e66;color:#fff}.admin-list-row{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #eee}.btn-sm{padding:6px 10px;background:#eef2f7;border-radius:8px;text-decoration:none}.alert{padding:12px;border-radius:8px;margin:12px 0}.alert-success{background:#d4edda}.alert-danger{background:#f8d7da}</style>
